[project]
name = "onyks-owl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "scipy>=1.15.2",
    "sympy>=1.13.3",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
yolo-ultralytics = [
    "torch>=2.4.1",
    "ultralytics>=8.3.107",
]

[tool.uv.workspace]
members = ["onyks_owl"]

[dependency-groups]
dev = [
    "notebook>=7.3.2",
    "pandas>=2.2.3",
]
exe = [
    "pyinstaller>=6.12.0",
]
test = [
    "pytest>=8.3.5",
]
