
minimize_params:
  method: nelder-mead
  options:
    disp: False
    maxiter: 50000

consts:
  width: 1920
  height: 1080
  sensor_h: 2.92
  sensor_w: 7.04

roi:
  x1: 0
  y1: 0
  x2: 1920
  y2: 1080

bounds:
  sensor_h: (2.80, 3.10)
  sensor_w: (6.90, 7.10)
  X: (-100, 100)
  Y: (40, 120)
  alpha: (-0.1, 0.1)
  beta: (-0.1, 0.1)
  gamma: (-0.1, 0.1)
  focus: (1.5, 6.0)
  scale: (1.0, 1.0)
  k1: (-0.2, 0.2)
  k2: (-0.2, 0.2)
  k3: (-0.2, 0.2)
  p1: (-0.2, 0.2)
  p2: (-0.2, 0.2)

init_values:
  sensor_h: 2.92
  sensor_w: 7.04
  X: 0
  Y: 0
  alpha: 0
  beta: 0
  gamma: 0
  focus: 4
  scale: 1
  k1: 0
  k2: 0
  k3: 0
  p1: 0
  p2: 0