// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Instance,
  InstanceFromJSON,
  InstanceToJSON,
  Queue,
  QueueFromJSON,
  QueueToJSON,
} from ".";

/**
 *
 * @export
 * @interface InstanceQueue
 */
export interface InstanceQueue {
  /**
   *
   * @type {string}
   * @memberof InstanceQueue
   */
  id?: string;
  /**
   *
   * @type {Instance}
   * @memberof InstanceQueue
   */
  projectInstance?: Instance;
  /**
   *
   * @type {Queue}
   * @memberof InstanceQueue
   */
  queue?: Queue;
}

export function InstanceQueueFromJSON(json: any): InstanceQueue {
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    projectInstance: !exists(json, "project_instance")
      ? undefined
      : InstanceFromJSON(json["project_instance"]),
    queue: !exists(json, "queue") ? undefined : QueueFromJSON(json["queue"]),
  };
}

export function InstanceQueueToJSON(value?: InstanceQueue): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    id: value.id,
    project_instance: InstanceToJSON(value.projectInstance),
    queue: QueueToJSON(value.queue),
  };
}
