// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { ModuleDef, ModuleDefFromJSON, ModuleDefToJSON } from ".";

/**
 * List of parameters aquired by calling module\'s class method ....
 * @export
 * @interface ModuleParamDef
 */
export interface ModuleParamDef {
  /**
   *
   * @type {ModuleDef}
   * @memberof ModuleParamDef
   */
  moduleDef?: ModuleDef;
  /**
   *
   * @type {string}
   * @memberof ModuleParamDef
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ModuleParamDef
   */
  description?: string;
  /**
   * Każdy typ powinien mieć dedykowany edytor w property managerze
   * @type {string}
   * @memberof ModuleParamDef
   */
  type: ModuleParamDefTypeEnum;
}

export function ModuleParamDefFromJSON(json: any): ModuleParamDef {
  return {
    moduleDef: !exists(json, "module_def")
      ? undefined
      : ModuleDefFromJSON(json["module_def"]),
    id: json["id"],
    description: !exists(json, "description") ? undefined : json["description"],
    type: json["type"],
  };
}

export function ModuleParamDefToJSON(value?: ModuleParamDef): any {
  if (value === undefined) {
    return undefined;
  }
  return {
    module_def: ModuleDefToJSON(value.moduleDef),
    id: value.id,
    description: value.description,
    type: value.type,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum ModuleParamDefTypeEnum {
  String = "string",
  Float = "float",
  Integer = "integer",
  Quad = "quad",
  Region = "region",
  RegionList = "region_list",
  Resource = "resource",
}
