# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.project import Project
from openapi_server import util

from openapi_server.models.project import Project  # noqa: E501

class Instance(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, project=None):  # noqa: E501
        """Instance - a model defined in OpenAPI

        :param id: The id of this Instance.  # noqa: E501
        :type id: str
        :param project: The project of this Instance.  # noqa: E501
        :type project: Project
        """
        self.openapi_types = {
            'id': str,
            'project': Project
        }

        self.attribute_map = {
            'id': 'id',
            'project': 'project'
        }

        self._id = id
        self._project = project

    @classmethod
    def from_dict(cls, dikt) -> 'Instance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Instance of this Instance.  # noqa: E501
        :rtype: Instance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Instance.


        :return: The id of this Instance.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Instance.


        :param id: The id of this Instance.
        :type id: str
        """

        self._id = id

    @property
    def project(self):
        """Gets the project of this Instance.


        :return: The project of this Instance.
        :rtype: Project
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this Instance.


        :param project: The project of this Instance.
        :type project: Project
        """

        self._project = project
