// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Instance,
    InstanceFromJSON,
    InstanceToJSON,
    Module,
    ModuleFromJSON,
    ModuleToJSON,
} from './';

/**
 * 
 * @export
 * @interface InstanceModule
 */
export interface InstanceModule  {
    /**
     * 
     * @type {string}
     * @memberof InstanceModule
     */
    id?: string;
    /**
     * 
     * @type {Instance}
     * @memberof InstanceModule
     */
    projectInstance?: Instance;
    /**
     * 
     * @type {Module}
     * @memberof InstanceModule
     */
    module?: Module;
}

export function InstanceModuleFromJSON(json: any): InstanceModule {
    return {
        'id': !exists(json, 'id') ? undefined : json['id'],
        'projectInstance': !exists(json, 'project_instance') ? undefined : InstanceFromJSON(json['project_instance']),
        'module': !exists(json, 'module') ? undefined : ModuleFromJSON(json['module']),
    };
}

export function InstanceModuleToJSON(value?: InstanceModule): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'project_instance': InstanceToJSON(value.projectInstance),
        'module': ModuleToJSON(value.module),
    };
}


