// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * List of module files in owl folder defining BaseModule descendant
 * @export
 * @interface ModuleDef
 */
export interface ModuleDef  {
    /**
     * 
     * @type {string}
     * @memberof ModuleDef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleDef
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleDef
     */
    description?: string;
}

export function ModuleDefFromJSON(json: any): ModuleDef {
    return {
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ModuleDefToJSON(value?: ModuleDef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'description': value.description,
    };
}


