// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Module,
    ModuleFromJSON,
    ModuleToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProjectResource
 */
export interface ProjectResource  {
    /**
     * 
     * @type {Module}
     * @memberof ProjectResource
     */
    project?: Module;
    /**
     * 
     * @type {Blob}
     * @memberof ProjectResource
     */
    url?: Blob;
}

export function ProjectResourceFromJSON(json: any): ProjectResource {
    return {
        'project': !exists(json, 'project') ? undefined : ModuleFromJSON(json['project']),
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function ProjectResourceToJSON(value?: ProjectResource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'project': ModuleToJSON(value.project),
        'url': value.url,
    };
}


