// tslint:disable
/**
 * Onyks Wagon Location API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Constant set of queue parameters, hardcoded in API
 * @export
 * @interface QueueParamDef
 */
export interface QueueParamDef  {
    /**
     * 
     * @type {string}
     * @memberof QueueParamDef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QueueParamDef
     */
    description?: string;
    /**
     * TODO: Każdy typ powinien mieć dedykowany edytor w property managerze
     * @type {string}
     * @memberof QueueParamDef
     */
    type: QueueParamDefTypeEnum;
}

export function QueueParamDefFromJSON(json: any): QueueParamDef {
    return {
        'id': json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': json['type'],
    };
}

export function QueueParamDefToJSON(value?: QueueParamDef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'description': value.description,
        'type': value.type,
    };
}

/**
* @export
* @enum {string}
*/
export enum QueueParamDefTypeEnum {
    String = 'string',
    Float = 'float',
    Integer = 'integer',
    Quad = 'quad',
    Region = 'region',
    RegionList = 'region_list',
    Resource = 'resource'
}


